[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
]


# Raspberry Pi 2, 3
# cross build --release --target arm-unknown-linux-gnueabihf

# Raspberry Pi Zero, 1
# cross build --release --target arm-unknown-linux-musleabi